n = input("nombre del cliente: ")
v = int(input("valor de la compra:" ))
descuento= v - (v * 0.08)
iva = descuento + (descuento * 0.10)
print(n)
print("valor de la venta ",v)
print("Descueto: 8%")
print("Con el descuento es: ",descuento)
print("incluyedo iva: ",iva)