print("Pasos para crear un repositorio en GitHub...")
input("Lo primero es entrar al navegador")
input("Buscar: GitHub")
input("Entrar en el primer enlace")
input("Luego que entres te registras en la pagina")
input("Luego que te registres entras en tu perfil")
input("le das en donde diga repositorio")
input("le das en: crear repositorio")
input("colocas el nombre del repositorio y una descripcion (lo ultimo es opcional)")
input("y ya con eso tienes un repositorio")