print("Buenas. Quisiera conocerte..")
n = input("¿Cual es tu nombre?:")
print(f"Mucho gusto en conocerte {n}.")
a = input("¿Cual es tu apellido?:")
ñ = int(input("Esta bien. ¿Cuantos años tienes?:"))
p = input("¿De que pais eres?:")
t = input("¿Actualmente estas laborando en algun lugar?:")
print("Entiendo. Entonces:")
print(f"tu nombre es {n} {a}")
print(f"Tienes {ñ} años")
print(f"Eres de {p}")
print(f"Y actualmente {t} estas laborando")